defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Zhuhua Hu (胡祝华)
subtitle: Professor, &nbsp Doctorial Tutor <br>Hainan University   

# left_side:
#   background_image: "./assets/huzhuhua.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: About Me
    link: /Brief-Bio
    icon: ""

  - text: News
    link: /
    icon: ""
    
  - text: Research (Systematic work)
    link: /Research
    icon: ""

  - text: Publications
    link: /Publications
    icon: ""

  - text: Courses
    link: /Courses
    icon: ""
    
  - text: Software & Hardware
    link: /Software_Hardware
    icon: ""
  
  - text: Awards and honors
    link: /Awards_honors
    icon: ""
    
  - text: Academic Service
    link: /Academic_Service
    icon: ""
    
  - text: Group Members
    link: /Group-Members
    icon: ""
    
  - text: Friends
    link: /Some_friends
    icon: ""

# Socialmedia Icons
social_icons:
  - name: mail
    link: mailto:eagler_hu@hainanu.edu.cn
    icon: icon brands fa fa-envelope

  - name: 163 mail
    link: mailto:eagler_hu@163.com
    icon: fab fa-google

  - name: github
    link: https://github.com/huzhuhua
    icon: fab fa-github-square


    
