defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Zhuhua Hu (胡祝华)
subtitle: Professor, &nbsp Doctorial Tutor <br>Hainan University   

# left_side:
#   background_image: "./assets/huzhuhua.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: About Me (简介)
    link: /Brief-Bio
    icon: ""

  - text: News （消息）
    link: /
    icon: ""
    
  - text: Research (系统性的工作)
    link: /Research
    icon: ""

  - text: Publications (成果发表)
    link: /Publications
    icon: ""
    
  - text: Software & Hardware (软硬件Demo系统)
    link: /Software_Hardware
    icon: ""
    
  - text: Courses (建设的课程)
    link: /Courses
    icon: ""
  
  - text: Awards and honors (获奖和荣誉)
    link: /Awards_honors
    icon: ""
    
  - text: Academic Service (学术活动)
    link: /Academic_Service
    icon: ""
    
  - text: Group Members (团队成员)
    link: /Group-Members
    icon: ""
    
  - text: Friends (合作者)
    link: /Some_friends
    icon: ""

# Socialmedia Icons
social_icons:
  - name: mail
    link: mailto:eagler_hu@hainanu.edu.cn
    icon: icon brands fa fa-envelope

  - name: 163 mail
    link: mailto:eagler_hu@163.com
    icon: fab fa-google

  - name: github
    link: https://github.com/huzhuhua
    icon: fab fa-github-square
